name: 'Build Snapshots'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Fetch Onkostar-API
        run: |
          curl -L --user dnpm:${{ secrets.PACKAGE_TOKEN }} \
            https://git.dnpm.dev/api/packages/Plugin-JF-Onkostar/generic/onkostar-api/2.11.1.6/onkostar-api-2.11.1.6.jar \
            --output ${{ github.workspace }}/libs/onkostar-api-2.11.1.6.jar

      - name: Create package
        run: mvn package

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: 'true'
          make_latest: 'true'
          generate_release_notes: 'true'
          files: |
            target/onkostar-plugin-dnpmexport*.jar